# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lisa.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lisa.proto',
  package='ingedata.lisa',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nlisa.proto\x12\ringedata.lisa\".\n\x08\x43\x61tegory\x12\r\n\x05label\x18\x01 \x01(\t\x12\x13\n\x0binstruction\x18\x02 \x01(\t\"5\n\x07Vector4\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"\xc0\x01\n\x0e\x43\x61meraMetadata\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\n\n\x02\x63x\x18\x03 \x01(\x02\x12\n\n\x02\x63y\x18\x04 \x01(\x02\x12)\n\tdirection\x18\x05 \x01(\x0b\x32\x16.ingedata.lisa.Vector4\x12(\n\x08position\x18\x06 \x01(\x0b\x32\x16.ingedata.lisa.Vector4\x12\n\n\x02r3\x18\x07 \x01(\x02\x12\n\n\x02r6\x18\x08 \x01(\x02\x12\n\n\x02r9\x18\t \x01(\x02\"\x89\x02\n\x04Lisa\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cinstructions\x18\x03 \x01(\t\x12\x13\n\x0b\x66rame_count\x18\x04 \x01(\r\x12\x37\n\ncategories\x18\x05 \x03(\x0b\x32#.ingedata.lisa.Lisa.CategoriesEntry\x12.\n\x07\x63\x61meras\x18\x06 \x03(\x0b\x32\x1d.ingedata.lisa.CameraMetadata\x1aJ\n\x0f\x43\x61tegoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.ingedata.lisa.Category:\x02\x38\x01\"w\n\x05\x46rame\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\x12\n\n\x02qx\x18\x06 \x01(\x02\x12\n\n\x02qy\x18\x07 \x01(\x02\x12\n\n\x02qz\x18\x08 \x01(\x02\x12\n\n\x02qw\x18\t \x01(\x02\x62\x06proto3')
)




_CATEGORY = _descriptor.Descriptor(
  name='Category',
  full_name='ingedata.lisa.Category',
  filename=None,
  file=DESCRIPTOR,

  containing_type=

  fields=[
    _descriptor.Fi
iptor(
      name='label'
ame='ingedata.lisa.Category.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),

      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,



      serialized_options=None, file=DESCRIPTOR)


    _descriptor.FieldDescriptor(
      name='instruction', full_name='ingedata.lisa.Category.instruction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=75,
)


_VECTOR4 = _descriptor.Descriptor(
  name='Vector4',
  full_name='ingedata.lisa.Vector4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ingedata.lisa.Vector4.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ingedata.lisa.Vector4.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ingedata.lisa.Vector4.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='ingedata.lisa.Vector4.w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=130,
)


_CAMERAMETADATA = _descriptor.Descriptor(
  name='CameraMetadata',
  full_name='ingedata.lisa.CameraMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='ingedata.lisa.CameraMetadata.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ingedata.lisa.CameraMetadata.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cx', full_name='ingedata.lisa.CameraMetadata.cx', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cy', full_name='ingedata.lisa.CameraMetadata.cy', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ingedata.lisa.CameraMetadata.direction', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='ingedata.lisa.CameraMetadata.position', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r3', full_name='ingedata.lisa.CameraMetadata.r3', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r6', full_name='ingedata.lisa.CameraMetadata.r6', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r9', full_name='ingedata.lisa.CameraMetadata.r9', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=325,
)


_LISA_CATEGORIESENTRY = _descriptor.Descriptor(
  name='CategoriesEntry',
  full_name='ingedata.lisa.Lisa.CategoriesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ingedata.lisa.Lisa.CategoriesEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ingedata.lisa.Lisa.CategoriesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=593,
)

_LISA = _descriptor.Descriptor(
  name='Lisa',
  full_name='ingedata.lisa.Lisa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ingedata.lisa.Lisa.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ingedata.lisa.Lisa.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instructions', full_name='ingedata.lisa.Lisa.instructions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_count', full_name='ingedata.lisa.Lisa.frame_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='categories', full_name='ingedata.lisa.Lisa.categories', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cameras', full_name='ingedata.lisa.Lisa.cameras', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LISA_CATEGORIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=593,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='ingedata.lisa.Frame',
  filename=None,
  file=DESCRIPTOR,
  
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qx', full_name='ingedata.lisa.Frame.qx', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qy', full_name='ingedata.lisa.Frame.qy', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ingedata.lisa.Frame.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ingedata.lisa.Frame.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='ingedata.lisa.Frame.x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ingedata.lisa.Frame.y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ingedata.lisa.Frame.z', index=4,
      number=5, type=2, cpp_type=6, label=1,      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qz', full_name='ingedata.lisa.Frame.qz', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qw', full_name='ingedata.lisa.Frame.qw', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=714,
)

_CAMERAMETADATA.fields_by_name['direction'].message_type = _VECTOR4
_CAMERAMETADATA.fields_by_name['position'].message_type = _VECTOR4
_LISA_CATEGORIESENTRY.fields_by_name['value'].message_type = _CATEGORY
_LISA_CATEGORIESENTRY.containing_type = _LISA
_LISA.fields_by_name['categories'].message_type = _LISA_CATEGORIESENTRY
_LISA.fields_by_name['cameras'].message_type = _CAMERAMETADATA
DESCRIPTOR.message_types_by_name['Category'] = _CATEGORY
DESCRIPTOR.message_types_by_name['Vector4'] = _VECTOR4
DESCRIPTOR.message_types_by_name['CameraMetadata'] = _CAMERAMETADATA
DESCRIPTOR.message_types_by_name['Lisa'] = _LISA
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), dict(
  DESCRIPTOR = _CATEGORY,
  __module__ = 'lisa_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lisa.Category)
  ))
_sym_db.RegisterMessage(Category)

Vector4 = _reflection.GeneratedProtocolMessageType('Vector4', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR4,
  __module__ = 'lisa_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lisa.Vector4)
  ))
_sym_db.RegisterMessage(Vector4)

CameraMetadata = _reflection.GeneratedProtocolMessageType('CameraMetadata', (_message.Message,), dict(
  DESCRIPTOR = _CAMERAMETADATA,
  __module__ = 'lisa_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lisa.CameraMetadata)
  ))
_sym_db.RegisterMessage(CameraMetadata)

Lisa = _reflection.GeneratedProtocolMessageType('Lisa', (_message.Message,), dict(

  CategoriesEntry = _reflection.GeneratedProtocolMessageType('CategoriesEntry', (_message.Message,), dict(
    DESCRIPTOR = _LISA_CATEGORIESENTRY,
    __module__ = 'lisa_pb2'
    # @@protoc_insertion_point(class_scope:ingedata.lisa.Lisa.CategoriesEntry)
    ))
  ,
  DESCRIPTOR = _LISA,
  __module__ = 'lisa_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lisa.Lisa)
  ))
_sym_db.RegisterMessage(Lisa)
_sym_db.RegisterMessage(Lisa.CategoriesEntry)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'lisa_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lisa.Frame)
  ))
_sym_db.RegisterMessage(Frame)


_LISA_CATEGORIESENTRY._options = None
# @@protoc_insertion_point(module_scope)
