# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='input.proto',
  package='ingedata.lidar',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0binput.proto\x12\x0eingedata.lidar\"?\n\x0eLidarDataPoint\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x12\x0c\n\x01i\x18\x04 \x01(\x02:\x01\x31\"@\n\x0eLidarDataFrame\x12.\n\x06points\x18\x01 \x03(\x0b\x32\x1e.ingedata.lidar.LidarDataPoint\"Z\n\x07\x45goPose\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x12\n\n\x02qx\x18\x04 \x02(\x02\x12\n\n\x02qy\x18\x05 \x02(\x02\x12\n\n\x02qz\x18\x06 \x02(\x02\x12\n\n\x02qw\x18\x07 \x02(\x02\"F\n\tImageData\x12\x0c\n\x04mime\x18\x01 \x02(\t\x12\r\n\x05width\x18\x02 \x02(\x05\x12\x0e\n\x06height\x18\x03 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\x0c\"N\n\x10ImageCalibration\x12\n\n\x02\x63x\x18\x01 \x02(\x02\x12\n\n\x02\x63y\x18\x02 \x02(\x02\x12\n\n\x02r3\x18\x04 \x02(\x02\x12\n\n\x02r5\x18\x06 \x02(\x02\x12\n\n\x02r7\x18\x08 \x02(\x02\"\xba\x01\n\x05Image\x12\x0e\n\x02\x63x\x18\x01 \x01(\x02:\x02-1\x12\x0e\n\x02\x63y\x18\x02 \x01(\x02:\x02-1\x12\n\n\x02\x64x\x18\x03 \x02(\x02\x12\n\n\x02\x64y\x18\x04 \x02(\x02\x12\n\n\x02\x64z\x18\x05 \x02(\x02\x12\r\n\x02\x64\x61\x18\x06 \x01(\x02:\x01\x30\x12\x35\n\x0b\x63\x61libration\x18\x07 \x01(\x0b\x32 .ingedata.lidar.ImageCalibration\x12\'\n\x04\x64\x61ta\x18\x08 \x02(\x0b\x32\x19.ingedata.lidar.ImageData\"o\n\x05\x46rame\x12\x10\n\x08position\x18\x01 \x02(\x05\x12-\n\x05lidar\x18\x02 \x02(\x0b\x32\x1e.ingedata.lidar.LidarDataFrame\x12%\n\x06images\x18\x03 \x03(\x0b\x32\x15.ingedata.lidar.Image')
)




_LIDARDATAPOINT = _descriptor.Descriptor(
  name='LidarDataPoint',
  full_name='ingedata.lidar.LidarDataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ingedata.lidar.LidarDataPoint.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ingedata.lidar.LidarDataPoint.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ingedata.lidar.LidarDataPoint.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='ingedata.lidar.LidarDataPoint.i', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=94,
)


_LIDARDATAFRAME = _descriptor.Descriptor(
  name='LidarDataFrame',
  full_name='ingedata.lidar.LidarDataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='ingedata.lidar.LidarDataFrame.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=160,
)


_EGOPOSE = _descriptor.Descriptor(
  name='EgoPose',
  full_name='ingedata.lidar.EgoPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ingedata.lidar.EgoPose.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='ingedata.lidar.EgoPose.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='ingedata.lidar.EgoPose.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qx', full_name='ingedata.lidar.EgoPose.qx', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qy', full_name='ingedata.lidar.EgoPose.qy', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qz', full_name='ingedata.lidar.EgoPose.qz', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qw', full_name='ingedata.lidar.EgoPose.qw', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=252,
)


_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='ingedata.lidar.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mime', full_name='ingedata.lidar.ImageData.mime', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='ingedata.lidar.ImageData.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ingedata.lidar.ImageData.height', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ingedata.lidar.ImageData.data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=324,
)


_IMAGECALIBRATION = _descriptor.Descriptor(
  name='ImageCalibration',
  full_name='ingedata.lidar.ImageCalibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cx', full_name='ingedata.lidar.ImageCalibration.cx', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cy', full_name='ingedata.lidar.ImageCalibration.cy', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r3', full_name='ingedata.lidar.ImageCalibration.r3', index=2,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r5', full_name='ingedata.lidar.ImageCalibration.r5', index=3,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='r7', full_name='ingedata.lidar.ImageCalibration.r7', index=4,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=404,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='ingedata.lidar.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cx', full_name='ingedata.lidar.Image.cx', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cy', full_name='ingedata.lidar.Image.cy', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dx', full_name='ingedata.lidar.Image.dx', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dy', full_name='ingedata.lidar.Image.dy', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dz', full_name='ingedata.lidar.Image.dz', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='da', full_name='ingedata.lidar.Image.da', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calibration', full_name='ingedata.lidar.Image.calibration', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ingedata.lidar.Image.data', index=7,
      number=8, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=593,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='ingedata.lidar.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='ingedata.lidar.Frame.position', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lidar', full_name='ingedata.lidar.Frame.lidar', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ingedata.lidar.Frame.images', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=706,
)

_LIDARDATAFRAME.fields_by_name['points'].message_type = _LIDARDATAPOINT
_IMAGE.fields_by_name['calibration'].message_type = _IMAGECALIBRATION
_IMAGE.fields_by_name['data'].message_type = _IMAGEDATA
_FRAME.fields_by_name['lidar'].message_type = _LIDARDATAFRAME
_FRAME.fields_by_name['images'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['LidarDataPoint'] = _LIDARDATAPOINT
DESCRIPTOR.message_types_by_name['LidarDataFrame'] = _LIDARDATAFRAME
DESCRIPTOR.message_types_by_name['EgoPose'] = _EGOPOSE
DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['ImageCalibration'] = _IMAGECALIBRATION
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LidarDataPoint = _reflection.GeneratedProtocolMessageType('LidarDataPoint', (_message.Message,), dict(
  DESCRIPTOR = _LIDARDATAPOINT,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.LidarDataPoint)
  ))
_sym_db.RegisterMessage(LidarDataPoint)

LidarDataFrame = _reflection.GeneratedProtocolMessageType('LidarDataFrame', (_message.Message,), dict(
  DESCRIPTOR = _LIDARDATAFRAME,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.LidarDataFrame)
  ))
_sym_db.RegisterMessage(LidarDataFrame)

EgoPose = _reflection.GeneratedProtocolMessageType('EgoPose', (_message.Message,), dict(
  DESCRIPTOR = _EGOPOSE,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.EgoPose)
  ))
_sym_db.RegisterMessage(EgoPose)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEDATA,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.ImageData)
  ))
_sym_db.RegisterMessage(ImageData)

ImageCalibration = _reflection.GeneratedProtocolMessageType('ImageCalibration', (_message.Message,), dict(
  DESCRIPTOR = _IMAGECALIBRATION,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.ImageCalibration)
  ))
_sym_db.RegisterMessage(ImageCalibration)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.Image)
  ))
_sym_db.RegisterMessage(Image)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'input_pb2'
  # @@protoc_insertion_point(class_scope:ingedata.lidar.Frame)
  ))
_sym_db.RegisterMessage(Frame)


# @@protoc_insertion_point(module_scope)
